{
 "title": "Alert",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cpu usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (sum(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by(instance) / count(node_cpu_seconds_total{mode=\"user\"}) by(instance))) * on(instance) group_left(node_name) node_meta{node_id=~\".+\"} * 100",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Nodes healthy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(node_meta{node_name=\"sladmin73\"}) by (node_name)",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "count(node_meta{node_name=\"sleader74\"}) by (node_name)",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "count(node_meta{node_name=\"swarm-master-60\"}) by (node_name)",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "count(node_meta{node_name=\"swarm-worker-95\"}) by (node_name)",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "count(node_meta{node_name=\"swarm-worker-96\"}) by (node_name)",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "count(node_meta{node_name=\"swarm-worker-97\"}) by (node_name)",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "count(node_meta{node_name=\"sladmin-91\"}) by (node_name)",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "count(node_meta{node_name=\"sladmin-92\"}) by (node_name)",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "count(node_meta{node_name=\"sladmin-76\"}) by (node_name)",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "count(node_meta{node_name=\"swarm-worker-51\"}) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Disk usage % by Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum((1 - (node_filesystem_free_bytes{mountpoint=\"/\"} / on(instance, device) node_filesystem_size_bytes{mountpoint=\"/\"}) * on(instance) group_left(node_name) node_meta{node_id=~\".*\"})) by (device, node_name)",
     "legendFormat": "Used {{node_name}}:{{device}}"
    }
   ]
  }
 ]
}