{
 "title": "MSSQL Exporter",
 "description": "Performance and health metrics for Prometheus MSSQL Exporter running on docker.",
 "tags": [ "SQL Server" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "database_name", "query": "mssql_database_size" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Databases properties", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"mssql-exporter\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "State OFFLINE",
     "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "singlestat",
   "description": "Number of lock requests per second that resulted in a deadlock since last restart",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mssql_session_blocked)",
     "measurement": "State ONLINE",
     "query": "SELECT \"total\" FROM \"State ONLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "CPU used",
   "type": "singlestat",
   "description": "Percentage of memory utilization",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(100-mssql_cpu_usage_idle)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU (%)",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "SQL process" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CPU usage" }
     ]
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "singlestat",
   "description": "Percentage of memory utilization",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(mssql_memory_utilization_percentage)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU (%)",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "SQL process" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CPU usage" }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "description": "Percentage of memory utilization",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(mssql_connections)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU (%)",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "SQL process" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CPU usage" }
     ]
    }
   ]
  },
  {
   "title": "Number of page faults",
   "type": "singlestat",
   "description": "Number of page faults since last restart",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(mssql_page_fault_count[$interval]))",
     "legendFormat": "Page Fault Count",
     "measurement": "State RECOVERY_PENDING",
     "query": "SELECT \"total\" FROM \"State RECOVERY_PENDING\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Physical Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "sum(mssql_os_memory) by(state)", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Page File",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(mssql_os_page_file) by(state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Database Sizes",
   "type": "table",
   "description": "Database Size information per instance",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 5 },
   "targets": [
    {
     "expr": "sum(mssql_database_size{db=~\"$database_name\"}) by(db)",
     "rawSql": "SELECT 1"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Active Connections",
   "type": "graph",
   "description": "Number of active connections",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mssql_connections{db=~\"$database_name\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Active Connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Write Stall Time (ms)",
   "type": "graph",
   "description": "Wait time (ms) of stall since last restart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms", "label": "Stall time" }
   ],
   "targets": [
    {
     "expr": "sum(mssql_io_stall_seconds{db=~\"$database_name\"}) by(db, operation)",
     "legendFormat": "{{db}} {{operation}}"
    }
   ]
  },
  {
   "title": "IO Stall Time (ms)",
   "type": "graph",
   "description": "Wait time (ms) of stall since last restart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "ms", "label": "Stall time" }
   ],
   "targets": [
    {
     "expr": "sum(mssql_io_stall_seconds{db=~\"$database_name\"}) by(db, operation)",
     "legendFormat": "{{db}}  {{operation}}"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Active Sessions",
   "type": "graph",
   "description": "Number of active connections",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mssql_session_meta{db=~\"$database_name\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Active Sessions",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Session Cpu Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mssql_session_last_cpu_used{db=~\"$database_name\"}[$interval])) by(loginame, hostname)",
     "legendFormat": "{{loginame}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Session Read&Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mssql_session_read_write{db=~\"$database_name\", operation=\"num_reads\"}[$interval])) by(loginame, hostname)",
     "legendFormat": "READ {{loginame}}@{{hostname}}"
    },
    {
     "expr": "- sum(rate(mssql_session_read_write{db=~\"$database_name\", operation=\"num_writes\"}[$interval])) by(loginame, hostname)",
     "legendFormat": "WRITE {{loginame}}@{{hostname}}"
    }
   ]
  }
 ]
}