{
 "title": "Docker Swarm Services",
 "description": "Docker Swarm stacks and services metrics",
 "tags": [ "swarmprom" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node_id", "label": "Swarm Node", "query": "node_meta" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "service", "label": "Service Name", "query": "container_last_seen" }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_swarm_node_id =~\"$node_id\", container_label_com_docker_swarm_service_name=~\"$service\"}) by (container_label_com_docker_swarm_node_id))"
    }
   ]
  },
  {
   "title": "Stacks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_stack_namespace=~\".+\", container_label_com_docker_swarm_node_id=~\"$node_id\", container_label_com_docker_swarm_service_name=~\"$service\"}) by (container_label_com_docker_stack_namespace))"
    }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_swarm_service_name=~\".+\", container_label_com_docker_swarm_node_id=~\"$node_id\", container_label_com_docker_swarm_service_name=~\"$service\"}) by (container_label_com_docker_swarm_service_name))"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{container_label_com_docker_swarm_node_id=~\"$node_id\", container_label_com_docker_swarm_service_name=~\"$service\"}[5m])) "
    }
   ]
  },
  {
   "title": "Running Containers by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(container_last_seen{container_label_com_docker_swarm_node_id=~\"$node_id\", container_label_com_docker_swarm_service_name=~\"$service\"}[5m])) by (container_label_com_docker_swarm_node_id)) * on(container_label_com_docker_swarm_node_id) group_left(node_name) node_meta",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(engine_daemon_health_checks_total[$interval]) * on(instance) group_left(node_id) swarm_node_info{node_id=~\"$node_id\"})  ",
     "legendFormat": "checks"
    },
    {
     "expr": "sum(increase(engine_daemon_health_checks_failed_total[$interval]) * on(instance) group_left(node_id) swarm_node_info{node_id=~\"$node_id\"})  ",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "CPU usage by Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_node_id=~\"$node_id\", container_label_com_docker_swarm_service_name=~\"$service\", id=~\"/docker/.*\"}[1m])) by (container_label_com_docker_swarm_service_name) * 100 ",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\"}[$interval]) * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"}) * 100 / count(node_cpu_seconds_total{mode=\"user\"} * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"}) "
    }
   ]
  },
  {
   "title": "CPU usage by Container (top 10)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_node_id=~\"$node_id\", container_label_com_docker_swarm_service_name=~\"$service\", id=~\"/docker/.*\"}[$interval])) by (name)) * 100 ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage by Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_com_docker_swarm_node_id=~\"$node_id\", container_label_com_docker_swarm_service_name=~\"$service\", id=~\"/docker/.*\"}) by (container_label_com_docker_swarm_service_name) ",
     "legendFormat": "Used {{container_label_com_docker_swarm_service_name}}"
    },
    {
     "expr": "sum(container_memory_cache{container_label_com_docker_swarm_node_id=~\"$node_id\", container_label_com_docker_swarm_service_name=~\"$service\", id=~\"/docker/.*\"}) by (container_label_com_docker_swarm_service_name) ",
     "legendFormat": "Cached {{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 26 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"} * 100) / count(node_meta * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"})"
    }
   ]
  },
  {
   "title": "Memory usage by Container (top 10)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, avg_over_time(container_memory_usage_bytes{container_label_com_docker_swarm_node_id=~\"$node_id\", container_label_com_docker_swarm_service_name=~\"$service\", id=~\"/docker/.*\"}[$interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network I/O by Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_node_id=~\"$node_id\", container_label_com_docker_swarm_service_name=~\"$service\"}[$interval])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "[IN] {{container_label_com_docker_swarm_service_name}}"
    },
    {
     "expr": "-1 * sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_node_id=~\"$node_id\", container_label_com_docker_swarm_service_name=~\"$service\"}[$interval])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "[OUT] {{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Disk I/O by Service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_fs_reads_bytes_total{container_label_com_docker_swarm_node_id=~\"$node_id\", container_label_com_docker_swarm_service_name=~\"$service\"}[$interval])) by (container_label_com_docker_swarm_node_id, container_label_com_docker_swarm_service_name)) * on(container_label_com_docker_swarm_node_id) group_left(node_name) node_meta != 0",
     "legendFormat": "[READ] {{ node_name }}/{{ container_label_com_docker_swarm_service_name }}"
    },
    {
     "expr": "- (sum(irate(container_fs_writes_bytes_total{container_label_com_docker_swarm_node_id=~\"$node_id\", container_label_com_docker_swarm_service_name=~\"$service\"}[$interval])) by (container_label_com_docker_swarm_node_id, container_label_com_docker_swarm_service_name)) * on(container_label_com_docker_swarm_node_id) group_left(node_name) node_meta != 0",
     "legendFormat": "[WRITE] {{ node_name }}/{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "Cluster Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total[$interval]))",
     "legendFormat": "Transmited"
    }
   ]
  },
  {
   "title": "Cluster IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_total{instance=~\"$service:.+\"}[$interval]))",
     "legendFormat": "Total Reads"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{instance=~\"$service:.+\"}[$interval]))",
     "legendFormat": "Total Writes"
    },
    {
     "expr": "sum(irate(container_fs_reads_total{container_label_com_docker_swarm_service_name=~\"$service\"}[$interval]))",
     "legendFormat": "Services Reads"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{container_label_com_docker_swarm_service_name=~\"$service\"}[$interval]))",
     "legendFormat": "Services Writes"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 56 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((node_filesystem_free_bytes{mountpoint=\"/rootfs\"} / node_filesystem_size_bytes{mountpoint=\"/rootfs\"}) * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"} * 100) / count(node_meta * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"})"
    }
   ]
  },
  {
   "title": "Docker Daemon Container Actions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(engine_daemon_container_actions_seconds_count * on(instance) group_left(node_id) swarm_node_info{node_id=~\"$node_id\"})  by (action)",
     "legendFormat": "{{action }}"
    }
   ]
  },
  {
   "title": "Docker Daemon Network Actions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(engine_daemon_network_actions_seconds_count * on(instance) group_left(node_id) swarm_node_info{node_id=~\"$node_id\"})  by (action)",
     "legendFormat": "{{action }}"
    }
   ]
  },
  {
   "title": "Docker Engine Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum(engine_daemon_engine_info * on(instance) group_left(node_id) swarm_node_info) by (kernel, os, graphdriver, version, node_id)"
    }
   ]
  }
 ]
}