{
 "title": "SLKE Node",
 "description": "New Dashboard for K8/OKD/OCP > 3.7",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "15s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Server Resource Overview",
   "type": "table-old",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{instance=~\"k8s.+\"})by(instance)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"k8s.+\", mode=\"idle\"}) by (instance)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"k8s.+\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "node_load5{instance=~\"k8s.+\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"k8s.+\", mode=\"idle\"}[5m])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"k8s.+\"} / (node_memory_MemTotal_bytes{instance=~\"k8s.+\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": " max((node_filesystem_size_bytes{instance=~\"k8s.+\", fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "max(irate(node_disk_read_bytes_total{instance=~\"k8s.+\"}[5m])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(irate(node_disk_written_bytes_total{instance=~\"k8s.+\"}[5m])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "max(irate(node_network_receive_bytes_total{instance=~\"k8s.+\"}[5m])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(irate(node_network_transmit_bytes_total{instance=~\"k8s.+\"}[5m])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  { "title": "Node Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Cpu%",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$interval])) by (instance) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Load 1min avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Nodes Readiness",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{status=\"true\",condition=\"Ready\"} > 0) / sum(kube_node_status_condition{status=\"true\",condition=\"Ready\"}) * 100",
     "legendFormat": "Atomic Nodes Readiness"
    }
   ]
  },
  {
   "title": "Nodes Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{status=\"true\"}) by (condition)",
     "legendFormat": "{{ condition }}"
    }
   ]
  },
  {
   "title": "Pods per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count((min(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1) * on(pod) group_left(node) (max(kube_pod_info) by(pod, node))) by(node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Total Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\"}) / sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Master Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 28 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\", node=~\"k8s-master.*\"}) / sum (node_memory_MemTotal_bytes{instance=~\"k8s-master.*\"})"
    }
   ]
  },
  {
   "title": "Worker Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 28 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\", node=~\"k8s-worker.*\"}) / sum (node_memory_MemTotal_bytes{instance=~\"k8s-worker.*\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 33 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 33 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 33 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"k8s-master.*\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 33 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\", node=~\"k8s-master.*\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 33 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"k8s-worker.*\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 33 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"k8s-worker.*\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Requeseted CPU%",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by (node) / count(label_replace(node_cpu_core_throttles_total, \"node\", \"$1\", \"instance\", \"(.+)\")) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Available CPUs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(node_cpu_core_throttles_total, \"node\", \"$1\", \"instance\", \"(.+)\")) by (node) - sum(kube_pod_container_resource_requests_cpu_cores) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Requeseted RAM%",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (node) / sum(label_replace(node_memory_MemTotal_bytes, \"node\", \"$1\", \"instance\", \"(.+)\")) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Available RAMs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(node_memory_MemTotal_bytes, \"node\", \"$1\", \"instance\", \"(.+)\")) by (node) - sum(kube_pod_container_resource_requests_memory_bytes) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}