{
 "title": "SLKE Service",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "15s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "kube_namespace_created{namespace!~\".*kube.*\", namespace!~\"openshift.*\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kubelet_node_name{node=~\"k8s-worker.*\"})",
     "legendFormat": "Worker Nodes"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(container_cpu_usage_seconds_total{node=~\"k8s-worker.*\", container!=\"POD\", pod!=\"\", container!=\"\", namespace=~\"$namespace\"})",
     "legendFormat": "Total Container"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg((1-rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"k8s-worker.*\"}[1m])))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\", container!=\"POD\", node=~\"k8s-worker.*\", container!=\"POD\", pod!=\"\", namespace=~\"$namespace\"})",
     "legendFormat": "RAM Used"
    }
   ]
  },
  { "title": "Activating", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Active Container by Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(container_cpu_usage_seconds_total{container!=\"\", node=~\"k8s-worker.*\", namespace!~\"openshift.*\", container!=\"POD\", pod!=\"\", namespace=~\"$namespace\"}) by(node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Active Container by Namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(container_cpu_usage_seconds_total{container!=\"\", node=~\"k8s-worker.*\", container!=\"POD\", pod!=\"\", namespace=~\"$namespace\"}) by(namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Namespace CPU%",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{node=~\"k8s-worker.*\", container!=\"POD\", pod!=\"\", namespace=~\"$namespace\"}[1m])) by(namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\", container!=\"POD\", node=~\"k8s-worker.*\", container!=\"POD\", pod!=\"\", namespace=~\"$namespace\"}) by(namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{container!=\"\", node=~\"k8s-worker.*\", pod!=\"\", namespace=~\"$namespace\"}[5m]) > 0) by (namespace)",
     "legendFormat": "[RX] {{namespace}}"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{container!=\"\", node=~\"k8s-worker.*\", pod!=\"\", namespace=~\"$namespace\"}[5m]) * -1 < 0) by (namespace)",
     "legendFormat": "[TX] {{namespace}}"
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Container CPU% > 10%",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{node=~\"k8s-worker.*\", cpu=\"total\", container!=\"POD\", pod!=\"\", namespace=~\"$namespace\"}[1m]) > 0.2",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Container RAM%",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{container!=\"\", node=~\"k8s-worker.*\", container!=\"POD\", pod!=\"\", namespace=~\"$namespace\"}) by (container, pod) / on(container, pod) group_left(namespace) max(kube_pod_container_resource_limits_memory_bytes{node=~\"k8s-worke.*\"}) by (container, pod)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Container RAM",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container!=\"\", node=~\"k8s-worker.*\", container!=\"POD\", pod!=\"\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(kube_pod_container_status_restarts_total{namespace=~\"$namespace\", namespace!~\"openshift.*\"}[5m]) > 0",
     "legendFormat": "{{ namespace }}/{{ pod }}/{{container}}"
    }
   ]
  }
 ]
}